"""shuju1

Revision ID: fe1f6d80c91c
Revises: 6291f38f2d83
Create Date: 2018-10-22 20:03:04.577152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1f6d80c91c'
down_revision = '6291f38f2d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('description', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'description')
    # ### end Alembic commands ###
